//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATAProdPall
    {
        public string CodProd { get; set; }
        public string Ref { get; set; }
        public string Marca { get; set; }
        public decimal CostoL { get; set; }
        public decimal CostoP { get; set; }
        public string Prov { get; set; }
    }
}
