//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAINTPALLEntities : DbContext
    {
        public SAINTPALLEntities()
            : base("name=SAINTPALLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Perspectiva> Perspectiva { get; set; }
        public virtual DbSet<SAEPRD> SAEPRD { get; set; }
        public virtual DbSet<SAFACT> SAFACT { get; set; }
        public virtual DbSet<SAPROD> SAPROD { get; set; }
        public virtual DbSet<MasterPerspectivaIndicador> MasterPerspectivaIndicador { get; set; }
        public virtual DbSet<Indicador> Indicador { get; set; }
    }
}
