//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyJoin
    {
        public string ID_Entity { get; set; }
        public string ID_SubEntity { get; set; }
        public int NLine { get; set; }
        public short Status { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
