//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPSistema
    {
        public string CodSucu { get; set; }
        public int Idversion { get; set; }
        public int UsaPantT { get; set; }
        public int TipoKeyB { get; set; }
        public int UsaImag { get; set; }
        public int UsaDescrip2 { get; set; }
        public int UsaDescrip3 { get; set; }
        public int UsaPeso { get; set; }
        public int UsaVolum { get; set; }
        public int UsaEmpaq { get; set; }
        public int TipoPvP { get; set; }
        public int TipoPvPLot { get; set; }
        public int UsaPrecioD { get; set; }
        public int TipoPvPD { get; set; }
        public int UsaDesgTax { get; set; }
        public int UsaDesgD { get; set; }
        public int UsaPorcD { get; set; }
        public string CodClie { get; set; }
        public string TextPvP { get; set; }
        public string TextDscto { get; set; }
        public string TextOfer { get; set; }
        public string TextIncTax { get; set; }
        public int TiempoRet { get; set; }
    }
}
