//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicador()
        {
            this.MasterPerspectivaIndicador = new HashSet<MasterPerspectivaIndicador>();
        }
    
        public int IDIndicador { get; set; }
        public string nombre { get; set; }
        public string objetivoEstrategico { get; set; }
        public Nullable<decimal> target { get; set; }
        public Nullable<decimal> rojo { get; set; }
        public Nullable<decimal> amarillo { get; set; }
        public Nullable<decimal> verde { get; set; }
        public string fecha { get; set; }
        public Nullable<decimal> conseguido { get; set; }
        public Nullable<int> IDPerspectiva { get; set; }
        public string CodItem { get; set; }
        public string FechaFin { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin2 { get; set; }
        public string NombreGerente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterPerspectivaIndicador> MasterPerspectivaIndicador { get; set; }
    }
}
