//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogLockReg
    {
        public int KeyRegLock { get; set; }
        public int IDStation { get; set; }
        public string ID_Entity { get; set; }
        public string TableName { get; set; }
        public short siPeriod { get; set; }
        public string IDGeneral { get; set; }
        public System.DateTime dtDate { get; set; }
        public short Status { get; set; }
    }
}
