//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPerspectivaIndicador
    {
        public int IDPerspectivaIndicador { get; set; }
        public Nullable<int> IDIndicador { get; set; }
        public Nullable<int> IDPerspectiva { get; set; }
    
        public virtual Perspectiva Perspectiva { get; set; }
        public virtual Indicador Indicador { get; set; }
    }
}
