//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelAccount()
        {
            this.CompaniyType = new HashSet<CompaniyType>();
        }
    
        public string ID_Account { get; set; }
        public string ID_Parent { get; set; }
        public string Descrip { get; set; }
        public string DescripShort { get; set; }
        public byte siLevel { get; set; }
        public bool boStatus { get; set; }
        public System.DateTime dtDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompaniyType> CompaniyType { get; set; }
    }
}
