//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipality
    {
        public string Descrip { get; set; }
        public string IDMunicipality { get; set; }
        public string IDCity { get; set; }
        public string IDState { get; set; }
        public string IDCountry { get; set; }
    }
}
