//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreciosSab
    {
        public string CodProd { get; set; }
        public decimal Precio1 { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public Nullable<decimal> PrecioU { get; set; }
        public decimal CostAct { get; set; }
        public decimal CostPro { get; set; }
        public decimal CostAnt { get; set; }
        public decimal PrecioU2 { get; set; }
        public decimal PrecioU3 { get; set; }
    }
}
