//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAACAMPOS
    {
        public string CodTbl { get; set; }
        public int NumGrp { get; set; }
        public string NombCpo { get; set; }
        public int TipoCpo { get; set; }
        public int Longitud { get; set; }
        public short Requerido { get; set; }
        public short CBusqueda { get; set; }
        public string AliasCpo { get; set; }
        public string Value { get; set; }
    }
}
