//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAACXC
    {
        public string CodClie { get; set; }
        public int NroUnico { get; set; }
        public System.DateTime FechaE { get; set; }
        public Nullable<System.DateTime> FechaV { get; set; }
        public string CodSucu { get; set; }
        public string CodEsta { get; set; }
        public string CodUsua { get; set; }
        public string CodOper { get; set; }
        public string CodVend { get; set; }
        public string NumeroD { get; set; }
        public short FromTran { get; set; }
        public string TipoCxc { get; set; }
        public string Moneda { get; set; }
        public decimal Factor { get; set; }
        public decimal MontoMEx { get; set; }
        public decimal SaldoMEx { get; set; }
        public string Document { get; set; }
        public string Notas1 { get; set; }
        public string Notas2 { get; set; }
        public string Notas3 { get; set; }
        public string Notas4 { get; set; }
        public string Notas5 { get; set; }
        public string Notas6 { get; set; }
        public string Notas7 { get; set; }
        public string Notas8 { get; set; }
        public string Notas9 { get; set; }
        public string Notas10 { get; set; }
        public decimal Monto { get; set; }
        public decimal MtoTax { get; set; }
        public decimal RetenIVA { get; set; }
        public decimal OrgTax { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<decimal> SaldoAct { get; set; }
        public short EsLibroI { get; set; }
        public decimal BaseImpo { get; set; }
        public decimal CancelI { get; set; }
        public decimal CancelA { get; set; }
        public decimal CancelE { get; set; }
        public decimal CancelC { get; set; }
        public decimal CancelT { get; set; }
        public decimal CancelG { get; set; }
        public decimal Comision { get; set; }
        public string DetalChq { get; set; }
        public short EsUnPago { get; set; }
        public short AfectaVta { get; set; }
        public short AfectaComi { get; set; }
        public short EsChqDev { get; set; }
        public short EsReten { get; set; }
        public Nullable<System.DateTime> UltIntMora { get; set; }
        public Nullable<System.DateTime> PrxVisita { get; set; }
        public int NroRegi { get; set; }
        public string NroCtrol { get; set; }
        public decimal MontoNeto { get; set; }
        public decimal SaldoOrg { get; set; }
        public Nullable<System.DateTime> FechaI { get; set; }
        public decimal CancelP { get; set; }
        public string NumeroD1 { get; set; }
        public Nullable<System.DateTime> FechaD1 { get; set; }
        public string NumeroT { get; set; }
        public string NumeroN { get; set; }
        public decimal TExento { get; set; }
        public Nullable<System.DateTime> FechaR { get; set; }
        public Nullable<System.DateTime> FechaT { get; set; }
        public decimal CancelD { get; set; }
        public short EsRetenIVA { get; set; }
        public decimal Debitos { get; set; }
        public decimal Creditos { get; set; }
        public short TipoTraE { get; set; }
        public string AutSRI { get; set; }
        public string NroEstable { get; set; }
        public string PtoEmision { get; set; }
        public string NumeroF { get; set; }
        public string NumeroP { get; set; }
    }
}
