//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAAGRUPOS
    {
        public string CodTbl { get; set; }
        public int NumGrp { get; set; }
        public string NombreGrp { get; set; }
        public short EsTrans { get; set; }
        public int NMeses { get; set; }
        public int NMovim { get; set; }
        public string AliasGrp { get; set; }
    }
}
