//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAATACXCRETMAN
    {
        public string CodClie { get; set; }
        public string NroPpal { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Valor { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public string FechaD { get; set; }
        public string NroRet { get; set; }
    }
}
