//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAATAVERS
    {
        public string Nombre { get; set; }
        public Nullable<int> Vers { get; set; }
        public string Licencia { get; set; }
        public string Fecha { get; set; }
    }
}
