//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACFAC
    {
        public int NroUnico { get; set; }
        public string TipoTra { get; set; }
        public string NumeroD { get; set; }
        public string CodEsta { get; set; }
        public string CodUsua { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public Nullable<System.DateTime> FechaT { get; set; }
    }
}
