//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACLPR
    {
        public int NroUnico { get; set; }
        public string CodItem { get; set; }
        public string CodClie { get; set; }
        public int EsServ { get; set; }
        public string REFERE { get; set; }
        public string TIPOFAC { get; set; }
        public string numerod { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio { get; set; }
        public Nullable<System.DateTime> fechae { get; set; }
    }
}
