//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACLIE_01
    {
        public string CodClie { get; set; }
        public string Tipo_de_Cliente { get; set; }
        public string Condicion { get; set; }
        public Nullable<int> Dias_de_Credito { get; set; }
        public string Status_Actual { get; set; }
        public Nullable<decimal> Limite_de_Credito { get; set; }
        public string Tiene_Tolerancia { get; set; }
        public Nullable<int> Dias_de_Tolerancia { get; set; }
        public string Observasiones_Informacion { get; set; }
    }
}
