//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACLIE
    {
        public string CodClie { get; set; }
        public string Descrip { get; set; }
        public string CodSucu { get; set; }
        public string ID3 { get; set; }
        public string Clase { get; set; }
        public string Represent { get; set; }
        public string Direc1 { get; set; }
        public string Direc2 { get; set; }
        public int Pais { get; set; }
        public int Estado { get; set; }
        public int Ciudad { get; set; }
        public string Telef { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string NIT { get; set; }
        public string CodZona { get; set; }
        public string CodVend { get; set; }
        public string CodConv { get; set; }
        public string CodFacL { get; set; }
        public short TipoCli { get; set; }
        public short TipoPVP { get; set; }
        public short IntMora { get; set; }
        public short EsGranCont { get; set; }
        public short EsCredito { get; set; }
        public decimal LimiteCred { get; set; }
        public int DiasCred { get; set; }
        public short EsToleran { get; set; }
        public int DiasTole { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public string Observa { get; set; }
        public decimal Saldo { get; set; }
        public decimal MontoMax { get; set; }
        public decimal MtoMaxCred { get; set; }
        public decimal PagosA { get; set; }
        public decimal PromPago { get; set; }
        public decimal RetenIVA { get; set; }
        public decimal Descto { get; set; }
        public Nullable<System.DateTime> FechaUV { get; set; }
        public decimal MontoUV { get; set; }
        public string NumeroUV { get; set; }
        public Nullable<System.DateTime> FechaUP { get; set; }
        public decimal MontoUP { get; set; }
        public string NumeroUP { get; set; }
        public short EsMoneda { get; set; }
        public string EdoKC { get; set; }
        public decimal SaldoPtos { get; set; }
        public short Activo { get; set; }
        public string Movil { get; set; }
        public string CodAlte { get; set; }
        public int TipoID3 { get; set; }
        public string DescOrder { get; set; }
        public int Municipio { get; set; }
        public string ZipCode { get; set; }
        public string DescripExt { get; set; }
        public short TipoID { get; set; }
    }
}
