//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACOMP2
    {
        public string TipoCom { get; set; }
        public string CodSucu { get; set; }
        public string CodEsta { get; set; }
        public string CodUsua { get; set; }
        public short Signo { get; set; }
        public string OTipo { get; set; }
        public string Moneda { get; set; }
        public decimal Factor { get; set; }
        public decimal MontoMEx { get; set; }
        public string CodUbic { get; set; }
        public string Descrip { get; set; }
        public string Direc1 { get; set; }
        public string Direc2 { get; set; }
        public int Pais { get; set; }
        public int Estado { get; set; }
        public int Ciudad { get; set; }
        public string Telef { get; set; }
        public string ID3 { get; set; }
        public string NIT { get; set; }
        public decimal Monto { get; set; }
        public decimal OtrosC { get; set; }
        public decimal MtoTax { get; set; }
        public decimal Fletes { get; set; }
        public decimal TGravable { get; set; }
        public decimal TExento { get; set; }
        public decimal DesctoP { get; set; }
        public decimal RetenIVA { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public Nullable<System.DateTime> FechaV { get; set; }
        public decimal CancelI { get; set; }
        public decimal CancelE { get; set; }
        public decimal CancelT { get; set; }
        public decimal CancelC { get; set; }
        public decimal CancelA { get; set; }
        public decimal CancelG { get; set; }
        public decimal Descto1 { get; set; }
        public decimal MtoInt1 { get; set; }
        public decimal Descto2 { get; set; }
        public decimal MtoInt2 { get; set; }
        public decimal MtoFinanc { get; set; }
        public string DetalChq { get; set; }
        public decimal TotalPrd { get; set; }
        public decimal TotalSrv { get; set; }
        public string OrdenC { get; set; }
        public string NumeroR { get; set; }
        public string CodOper { get; set; }
        public int NGiros { get; set; }
        public int NMeses { get; set; }
        public string Notas1 { get; set; }
        public string Notas2 { get; set; }
        public string Notas3 { get; set; }
        public string Notas4 { get; set; }
        public string Notas5 { get; set; }
        public string Notas6 { get; set; }
        public string Notas7 { get; set; }
        public string Notas8 { get; set; }
        public string Notas9 { get; set; }
        public string Notas10 { get; set; }
        public short EsConsig { get; set; }
        public string TipoTra { get; set; }
        public string NroCtrol { get; set; }
        public string NumeroD { get; set; }
        public string ONumero { get; set; }
        public string NumeroC { get; set; }
        public string CodProv { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public decimal SaldoAct { get; set; }
        public decimal MtoPagos { get; set; }
        public decimal MtoNCredito { get; set; }
        public decimal MtoNDebito { get; set; }
        public Nullable<System.DateTime> FechaI { get; set; }
        public string NumeroN { get; set; }
        public string NumeroP { get; set; }
        public string NumeroE { get; set; }
        public decimal MtoTotal { get; set; }
        public decimal Contado { get; set; }
        public decimal Credito { get; set; }
        public Nullable<System.DateTime> FechaR { get; set; }
        public Nullable<System.DateTime> FechaT { get; set; }
        public int NROUNICO { get; set; }
    }
}
