//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACONF
    {
        public string CodSucu { get; set; }
        public string Descrip { get; set; }
        public string Direc1 { get; set; }
        public string Direc2 { get; set; }
        public string Email { get; set; }
        public string Telef { get; set; }
        public string RIF { get; set; }
        public string NIT { get; set; }
        public int Ciudad { get; set; }
        public int Estado { get; set; }
        public int Pais { get; set; }
        public string SPais { get; set; }
        public string SEstado { get; set; }
        public string SCiudad { get; set; }
        public string CodTaxs { get; set; }
        public int IdVersion { get; set; }
        public int IdVerXtra { get; set; }
        public string MesCurso { get; set; }
        public int MesTran { get; set; }
        public int MesOC { get; set; }
        public int MesPrf { get; set; }
        public decimal CostoMes { get; set; }
        public short CorrelPrd { get; set; }
        public decimal MtoExtraG { get; set; }
        public short ImpFleteV { get; set; }
        public short ImpFleteC { get; set; }
        public short PagaReten { get; set; }
        public short AutoReten { get; set; }
        public decimal PorctReten { get; set; }
        public short Redond { get; set; }
        public short RedTotal { get; set; }
        public short ObliOper { get; set; }
        public int PaswLim { get; set; }
        public byte[] Adicional { get; set; }
        public decimal Factor { get; set; }
        public short EsMoneda { get; set; }
        public Nullable<short> PedirNCtrl { get; set; }
        public Nullable<short> RetenIsrl { get; set; }
        public decimal ValorPtos { get; set; }
        public int MesesPtos { get; set; }
        public Nullable<System.DateTime> FechaUC { get; set; }
        public decimal FactorM { get; set; }
        public short UsaFactorM { get; set; }
        public string SimbFac { get; set; }
        public short UsaNEL { get; set; }
        public short InvConsig { get; set; }
        public short PrioridadIC { get; set; }
        public short CorrelUNC { get; set; }
        public byte[] Imagen { get; set; }
        public short RetenIVA { get; set; }
        public int Municipio { get; set; }
        public string SMunicipio { get; set; }
        public string ZipCode { get; set; }
        public int IdAppNot { get; set; }
        public string NroSerial { get; set; }
        public string KeySerial { get; set; }
        public string NroEstable { get; set; }
        public decimal ValorPtosV { get; set; }
        public string RUCUser { get; set; }
        public string RUCPwd { get; set; }
        public string EstablReten { get; set; }
        public string PtoEmiReten { get; set; }
        public Nullable<System.DateTime> FecCadReten { get; set; }
        public string AutSRIReten { get; set; }
        public short TipoFac { get; set; }
        public int CorrelEstac { get; set; }
        public string IMailHost { get; set; }
        public int IMailPort { get; set; }
        public string IMailUser { get; set; }
        public string IMailPwd { get; set; }
        public string IMailSender { get; set; }
        public Nullable<int> TipFac { get; set; }
    }
}
