//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACORRELSIS
    {
        public string CodSucu { get; set; }
        public string Fieldname { get; set; }
        public string ValueStr { get; set; }
        public int ValueInt { get; set; }
        public decimal ValueDec { get; set; }
        public string CodEsta { get; set; }
    }
}
