//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACONPRECIO
    {
        public short UsaPTactil { get; set; }
        public short UsaDescrip2 { get; set; }
        public short UsaDescrip3 { get; set; }
        public short UsaImagen { get; set; }
        public short TipoPVP { get; set; }
        public short PVPLote { get; set; }
        public short UsaTax { get; set; }
        public short UsaDscto { get; set; }
        public short UsaPorcD { get; set; }
        public string CodClie { get; set; }
        public string TextInf1 { get; set; }
        public string TextInf2 { get; set; }
        public string TextInf3 { get; set; }
        public string TextInf4 { get; set; }
        public string TextInf5 { get; set; }
        public byte[] Logo { get; set; }
        public string TextPrecio { get; set; }
        public string TextIncTax { get; set; }
        public string TextDscto { get; set; }
        public string TextOferta { get; set; }
    }
}
