//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACORTEZ
    {
        public int NROUNICO { get; set; }
        public string CodSucu { get; set; }
        public string CodEsta { get; set; }
        public string CodUsua { get; set; }
        public string NumeroP { get; set; }
        public string NumeroZ { get; set; }
        public decimal MtoTotal { get; set; }
        public string NumeroF { get; set; }
        public int NroFacts { get; set; }
        public string NumeroR { get; set; }
        public decimal MtoTax { get; set; }
        public decimal TExento { get; set; }
        public decimal MtoTotal1 { get; set; }
        public decimal MtoTax1 { get; set; }
        public decimal MtoTotal2 { get; set; }
        public decimal MtoTax2 { get; set; }
        public decimal MtoTotal3 { get; set; }
        public decimal MtoTax3 { get; set; }
        public decimal TDevExento { get; set; }
        public decimal DevMtoTotal { get; set; }
        public decimal DevMtoTotal1 { get; set; }
        public decimal DevMtoTax1 { get; set; }
        public decimal DevMtoTotal2 { get; set; }
        public decimal DevMtoTax2 { get; set; }
        public decimal DevMtoTotal3 { get; set; }
        public decimal DevMtoTax3 { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public string NumeroC { get; set; }
        public int NroDevol { get; set; }
    }
}
