//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SADEPO_01
    {
        public string CodUbic { get; set; }
        public int NroUnico { get; set; }
        public System.DateTime FecTrn { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Precio1 { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public Nullable<decimal> Preciou1 { get; set; }
        public Nullable<decimal> Preciou2 { get; set; }
        public Nullable<decimal> Preciou3 { get; set; }
    }
}
