//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAECOM
    {
        public string Periodo { get; set; }
        public string CodSucu { get; set; }
        public decimal MtoCompra { get; set; }
        public decimal MtoTax { get; set; }
        public decimal Descto { get; set; }
        public decimal Fletes { get; set; }
        public decimal Contado { get; set; }
        public decimal Credito { get; set; }
        public int NroComps { get; set; }
        public int NroDevol { get; set; }
    }
}
