//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAECLI
    {
        public string CodClie { get; set; }
        public string Periodo { get; set; }
        public int NroFacts { get; set; }
        public decimal Credito { get; set; }
        public decimal Contado { get; set; }
        public decimal Descto { get; set; }
        public decimal Costo { get; set; }
        public decimal MtoDevol { get; set; }
        public int NroDevol { get; set; }
        public decimal MtoPagos { get; set; }
        public int NroPagos { get; set; }
        public decimal MtoNDebito { get; set; }
        public int NroNDebito { get; set; }
        public decimal MtoNCredito { get; set; }
        public int NroNCredito { get; set; }
        public decimal MtoRetenImp { get; set; }
    }
}
