//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAEOPI
    {
        public string Periodo { get; set; }
        public string CodSucu { get; set; }
        public decimal MtoCargos { get; set; }
        public decimal MtoDescarg { get; set; }
        public decimal MtoTraslad { get; set; }
        public int CntCargos { get; set; }
        public int CntDescarg { get; set; }
        public int CntTraslad { get; set; }
    }
}
