//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAEPRD
    {
        public string CodProd { get; set; }
        public string Periodo { get; set; }
        public decimal ExInicial { get; set; }
        public decimal MtoCompra { get; set; }
        public decimal CntCompra { get; set; }
        public decimal MtoVentas { get; set; }
        public decimal CntVentas { get; set; }
        public decimal Costo { get; set; }
        public decimal MtoCargos { get; set; }
        public decimal CntCargos { get; set; }
        public decimal MtoDescarg { get; set; }
        public decimal CntDescarg { get; set; }
        public decimal CntInicial { get; set; }
        public decimal ExFinal { get; set; }
        public decimal CostoFinal { get; set; }
    }
}
