//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAETAR
    {
        public string CodTarj { get; set; }
        public string Periodo { get; set; }
        public decimal MtoVentas { get; set; }
        public decimal MtoRetenImp { get; set; }
        public decimal Impuesto { get; set; }
        public decimal MtoTotReten { get; set; }
        public decimal MtoTips { get; set; }
        public decimal MtoIngreso { get; set; }
        public decimal MtoCompra { get; set; }
    }
}
