//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAEXIS
    {
        public string CodProd { get; set; }
        public string CodUbic { get; set; }
        public string PuestoI { get; set; }
        public decimal Existen { get; set; }
        public decimal ExUnidad { get; set; }
        public string CodAttr1 { get; set; }
        public string CodAttr2 { get; set; }
        public string CodAttr3 { get; set; }
        public decimal CantPed { get; set; }
        public decimal UnidPed { get; set; }
        public decimal CantCom { get; set; }
        public decimal UnidCom { get; set; }
    }
}
