//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAEXISCON
    {
        public string CodProd { get; set; }
        public string CodUbic { get; set; }
        public string CodAlte { get; set; }
        public int NroUnico { get; set; }
        public string TipoTra { get; set; }
        public string NumeroD { get; set; }
        public decimal Cantidad { get; set; }
        public short EsUnid { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public Nullable<System.DateTime> FechaV { get; set; }
        public decimal Monto { get; set; }
        public int NroLinea { get; set; }
        public string NumeroK { get; set; }
    }
}
