//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAFALO
    {
        public string CodFacL { get; set; }
        public string CodSucu { get; set; }
        public string Descrip { get; set; }
        public int DiasCred { get; set; }
        public string CodVend { get; set; }
        public string CodOper { get; set; }
        public short TipoFac { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public short TipoOpe { get; set; }
    }
}
