//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAFIEL
    {
        public string tablename { get; set; }
        public string fieldname { get; set; }
        public string fieldalias { get; set; }
        public string datatype { get; set; }
        public string selectable { get; set; }
        public string searchable { get; set; }
        public string sortable { get; set; }
        public string autosearch { get; set; }
        public string mandatory { get; set; }
    }
}
