//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAINSTA
    {
        public int CodInst { get; set; }
        public string Descrip { get; set; }
        public string CodAlte { get; set; }
        public int Nivel { get; set; }
        public int InsPadre { get; set; }
        public int CodCate { get; set; }
        public int CatPadre { get; set; }
        public decimal Descto { get; set; }
        public short DEsComp { get; set; }
        public short DEsProdu { get; set; }
        public short DEsSeri { get; set; }
        public short DEsLote { get; set; }
        public short DEsVence { get; set; }
        public short DEsComi { get; set; }
        public short DEsCorrel { get; set; }
        public short DigitosC { get; set; }
        public short DEsTabla { get; set; }
        public short TipoIns { get; set; }
        public short DEsAttr1 { get; set; }
        public short DEsAttr2 { get; set; }
        public short DEsAttr3 { get; set; }
        public string EdoKC { get; set; }
    }
}
