//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAINITI
    {
        public string CodProd { get; set; }
        public string CodUbic { get; set; }
        public string Periodo { get; set; }
        public decimal ExInicial { get; set; }
        public decimal ExUndIni { get; set; }
        public decimal ExFinal { get; set; }
        public decimal ExUndFinal { get; set; }
        public decimal Costo { get; set; }
        public decimal CostoFinal { get; set; }
    }
}
