//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAIPAVTA
    {
        public string TipoFac { get; set; }
        public string NumeroD { get; set; }
        public int NroUnico { get; set; }
        public int TipoPag { get; set; }
        public string CodPago { get; set; }
        public string Descrip { get; set; }
        public decimal Monto { get; set; }
        public decimal Propina { get; set; }
        public decimal Impuesto { get; set; }
        public decimal RetencT { get; set; }
        public string Descrip1 { get; set; }
        public string Cuenta { get; set; }
        public string NroLote { get; set; }
        public string Afiliado { get; set; }
        public string Terminal { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public string Aprobado { get; set; }
        public string Refere { get; set; }
        public string Traza { get; set; }
        public string CodSucu { get; set; }
    }
}
