//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAITEO
    {
        public string NumeroD { get; set; }
        public int NroUnico { get; set; }
        public string CodItem { get; set; }
        public short TipoOfe { get; set; }
        public short Medida { get; set; }
        public decimal Monto { get; set; }
        public decimal Comision { get; set; }
        public decimal Desde { get; set; }
        public decimal Hasta { get; set; }
    }
}
