//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAITFL
    {
        public string CodFacL { get; set; }
        public int NroUnico { get; set; }
        public short EsServ { get; set; }
        public short EsUnid { get; set; }
        public string CodItem { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
    }
}
