//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAITCV
    {
        public string CodConv { get; set; }
        public int NroUnico { get; set; }
        public string CodItem { get; set; }
        public short TipoCnv { get; set; }
        public short Medida { get; set; }
        public decimal Monto { get; set; }
        public decimal Comision { get; set; }
        public decimal Desde { get; set; }
        public decimal Hasta { get; set; }
        public int Frecuencia { get; set; }
        public decimal MontoMax { get; set; }
        public Nullable<System.DateTime> FechaUV { get; set; }
        public short TipoPVP { get; set; }
    }
}
