//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAITOR
    {
        public int TipoTra { get; set; }
        public string NumeroK { get; set; }
        public string CodUbic { get; set; }
        public string CodProd { get; set; }
        public int NroLinea { get; set; }
        public string TipoOpI { get; set; }
        public int Status { get; set; }
        public decimal Precio { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Descto { get; set; }
        public decimal MtoTax1 { get; set; }
        public decimal MtoTax2 { get; set; }
        public decimal MtoTax3 { get; set; }
        public decimal MtoTax4 { get; set; }
        public decimal MtoTax5 { get; set; }
    }
}
