//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAITEMPLANI
    {
        public string NumeroD { get; set; }
        public int NroLinea { get; set; }
        public Nullable<int> NroRegi { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public Nullable<System.DateTime> FechaV { get; set; }
        public string TipoCxC { get; set; }
        public string NumeroC { get; set; }
        public string Document { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> CancelI { get; set; }
        public Nullable<decimal> CancelA { get; set; }
        public Nullable<decimal> CancelE { get; set; }
        public Nullable<decimal> CancelC { get; set; }
        public Nullable<decimal> CancelT { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public string DetalChq { get; set; }
        public Nullable<System.DateTime> PrxVisita { get; set; }
        public string CodSucu { get; set; }
    }
}
