//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAITEMFAC2
    {
        public string TipoFac { get; set; }
        public string NumeroD { get; set; }
        public string OTipo { get; set; }
        public string ONumero { get; set; }
        public short Estado { get; set; }
        public int NroLinea { get; set; }
        public int NroLineaC { get; set; }
        public string CodItem { get; set; }
        public string CodUbic { get; set; }
        public string CodMeca { get; set; }
        public string CodVend { get; set; }
        public short DEsAttr1 { get; set; }
        public string CodAttr1 { get; set; }
        public short DEsAttr2 { get; set; }
        public string CodAttr2 { get; set; }
        public short DEsAttr3 { get; set; }
        public string CodAttr3 { get; set; }
        public string Descrip1 { get; set; }
        public string Descrip2 { get; set; }
        public string Descrip3 { get; set; }
        public string Descrip4 { get; set; }
        public string Descrip5 { get; set; }
        public string Descrip6 { get; set; }
        public string Descrip7 { get; set; }
        public string Descrip8 { get; set; }
        public string Descrip9 { get; set; }
        public string Descrip10 { get; set; }
        public string Refere { get; set; }
        public short Signo { get; set; }
        public decimal CantMayor { get; set; }
        public decimal Cantidad { get; set; }
        public decimal CantidadU { get; set; }
        public decimal CantidadA { get; set; }
        public decimal CantidadUA { get; set; }
        public decimal Costo { get; set; }
        public decimal Precio { get; set; }
        public decimal Descto { get; set; }
        public string NroLote { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public Nullable<System.DateTime> FechaL { get; set; }
        public Nullable<System.DateTime> FechaV { get; set; }
        public short EsServ { get; set; }
        public short EsUnid { get; set; }
        public short EsFreeP { get; set; }
        public short EsPesa { get; set; }
        public short EsExento { get; set; }
        public short UsaServ { get; set; }
        public short DEsLote { get; set; }
        public short DEsSeri { get; set; }
        public short DEsComp { get; set; }
        public decimal CantidadC { get; set; }
        public decimal ExistAnt { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> CantidadO { get; set; }
        public Nullable<decimal> ExistAntU { get; set; }
        public Nullable<int> NroUnicoL { get; set; }
        public Nullable<decimal> Tara { get; set; }
        public Nullable<decimal> TotalItem { get; set; }
        public string NumeroE { get; set; }
    }
}
