//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALOTE
    {
        public string CodProd { get; set; }
        public int NroUnico { get; set; }
        public string CodUbic { get; set; }
        public string NroLote { get; set; }
        public decimal Costo { get; set; }
        public decimal Precio { get; set; }
        public decimal PrecioU { get; set; }
        public decimal Cantidad { get; set; }
        public decimal CantidadU { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public Nullable<System.DateTime> FechaV { get; set; }
        public decimal Precio1 { get; set; }
        public decimal PrecioU1 { get; set; }
        public decimal Precio2 { get; set; }
        public decimal PrecioU2 { get; set; }
        public decimal Precio3 { get; set; }
        public decimal PrecioU3 { get; set; }
        public string PuestoI { get; set; }
    }
}
