//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAORDT
    {
        public int TipoTra { get; set; }
        public string NumeroK { get; set; }
        public string CodUbic { get; set; }
        public int Status { get; set; }
        public string TipoOpI { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public Nullable<System.DateTime> FechaV { get; set; }
        public int TipoCli { get; set; }
        public string Descrip { get; set; }
        public string Direc1 { get; set; }
        public string Direc2 { get; set; }
        public string Direc3 { get; set; }
        public string Telef { get; set; }
        public string ID3 { get; set; }
        public string NIT { get; set; }
        public decimal Monto { get; set; }
        public decimal Descto { get; set; }
        public decimal MtoTax1 { get; set; }
        public decimal MtoTax2 { get; set; }
        public decimal MtoTax3 { get; set; }
        public decimal MtoTax4 { get; set; }
        public decimal MtoTax5 { get; set; }
        public int EsExPickup { get; set; }
        public string TipoPago { get; set; }
        public string DescripPago { get; set; }
        public string Courier { get; set; }
    }
}
