//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPAGCXPHist
    {
        public int NroPpal { get; set; }
        public int NroUnico { get; set; }
        public int NroRegi { get; set; }
        public string TipoCxP { get; set; }
        public decimal MontoDocA { get; set; }
        public decimal Monto { get; set; }
        public string NumeroD { get; set; }
        public string Descrip { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public Nullable<System.DateTime> FechaO { get; set; }
        public short EsReten { get; set; }
        public decimal BaseReten { get; set; }
        public string CodOper { get; set; }
        public string CodRete { get; set; }
        public decimal BaseImpo { get; set; }
        public decimal TExento { get; set; }
        public decimal MtoTax { get; set; }
        public decimal RetenIVA { get; set; }
        public short EsRetenIVA { get; set; }
        public short Sustraendo { get; set; }
    }
}
