//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPAIS
    {
        public string Descrip { get; set; }
        public int Pais { get; set; }
        public string SPais { get; set; }
        public string SEstado { get; set; }
        public string SCiudad { get; set; }
        public string SMunicipio { get; set; }
    }
}
