//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPLANI
    {
        public string NumeroD { get; set; }
        public string CodClie { get; set; }
        public Nullable<int> NroPpal { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public Nullable<System.DateTime> FechaV { get; set; }
        public string CodSucu { get; set; }
        public string CodEsta { get; set; }
        public string CodUsua { get; set; }
        public string CodOper { get; set; }
        public string CodVend { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Autori { get; set; }
        public string Respon { get; set; }
        public string Notas1 { get; set; }
        public string Notas2 { get; set; }
        public string Notas3 { get; set; }
        public string Notas4 { get; set; }
        public string Notas5 { get; set; }
        public string Notas6 { get; set; }
        public string Notas7 { get; set; }
        public string Notas8 { get; set; }
        public string Notas9 { get; set; }
        public string Notas10 { get; set; }
    }
}
