//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPRIMCOM
    {
        public string CodProv { get; set; }
        public string TipoCom { get; set; }
        public string NumeroD { get; set; }
        public int NroLinea { get; set; }
        public string DocImpo { get; set; }
        public string CodItem { get; set; }
        public decimal Factor { get; set; }
        public string Moneda { get; set; }
        public Nullable<System.DateTime> FechaI { get; set; }
        public decimal PrecioU { get; set; }
        public decimal Precio1 { get; set; }
        public decimal Precio2 { get; set; }
        public decimal Precio3 { get; set; }
        public decimal PrecioI1 { get; set; }
        public decimal PrecioI2 { get; set; }
        public decimal PrecioI3 { get; set; }
        public decimal Costo1 { get; set; }
        public decimal Costo2 { get; set; }
        public decimal Costo3 { get; set; }
        public decimal Costo4 { get; set; }
        public decimal Costo5 { get; set; }
        public decimal Costo6 { get; set; }
        public decimal Costo7 { get; set; }
        public decimal Costo8 { get; set; }
        public decimal Costo9 { get; set; }
        public decimal Costo10 { get; set; }
        public decimal PrecioU2 { get; set; }
        public decimal PrecioU3 { get; set; }
        public string CodSucu { get; set; }
        public int NroLineaC { get; set; }
    }
}
