//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPROD_02
    {
        public string CodProd { get; set; }
        public string Descripcion { get; set; }
        public string Referencia { get; set; }
        public string Proveedor { get; set; }
        public string Nombre_Proveedor { get; set; }
        public string Marca { get; set; }
        public Nullable<decimal> Costo_Lista { get; set; }
        public Nullable<decimal> Costo_Pall { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo_Precios { get; set; }
        public string Exhibido { get; set; }
        public string Regulado { get; set; }
        public Nullable<System.DateTime> Fecha_U_C { get; set; }
        public string Clasificacion { get; set; }
    }
}
