//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPROD_03
    {
        public string CodProd { get; set; }
        public string Tiempo { get; set; }
        public string Taller { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Modelo { get; set; }
    }
}
