//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPRSRI
    {
        public string CODPROV { get; set; }
        public string NroEstable { get; set; }
        public string PtoEmision { get; set; }
        public Nullable<System.DateTime> FechaV { get; set; }
        public int NroInicio { get; set; }
        public int NroFinal { get; set; }
        public string AutSRI { get; set; }
    }
}
