//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPROV_01
    {
        public string CodProv { get; set; }
        public int NroUnico { get; set; }
        public System.DateTime FecTrn { get; set; }
        public string Descuento { get; set; }
        public string Concepto { get; set; }
        public string Observacion { get; set; }
    }
}
