//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPROD
    {
        public string CodProd { get; set; }
        public int CodInst { get; set; }
        public string Descrip { get; set; }
        public string Descrip2 { get; set; }
        public string Descrip3 { get; set; }
        public string Refere { get; set; }
        public string Marca { get; set; }
        public string Unidad { get; set; }
        public string UndEmpaq { get; set; }
        public decimal CantEmpaq { get; set; }
        public Nullable<decimal> Precio1 { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public Nullable<decimal> PrecioU { get; set; }
        public decimal CostAct { get; set; }
        public decimal CostPro { get; set; }
        public decimal CostAnt { get; set; }
        public decimal Existen { get; set; }
        public decimal ExUnidad { get; set; }
        public decimal Compro { get; set; }
        public decimal Pedido { get; set; }
        public int Solici { get; set; }
        public decimal Minimo { get; set; }
        public decimal Maximo { get; set; }
        public decimal Tara { get; set; }
        public short DEsComp { get; set; }
        public short DEsComi { get; set; }
        public short DEsSeri { get; set; }
        public short DEsProdu { get; set; }
        public short DEsLote { get; set; }
        public short DEsVence { get; set; }
        public short DEsTabla { get; set; }
        public short DEsPsico { get; set; }
        public short DEsAttr1 { get; set; }
        public short DEsAttr2 { get; set; }
        public short DEsAttr3 { get; set; }
        public short EsPublish { get; set; }
        public short EsImport { get; set; }
        public short EsExento { get; set; }
        public short EsEnser { get; set; }
        public short EsOferta { get; set; }
        public short EsPesa { get; set; }
        public short EsEmpaque { get; set; }
        public short ExDecimal { get; set; }
        public int DiasEntr { get; set; }
        public Nullable<System.DateTime> FechaUV { get; set; }
        public Nullable<System.DateTime> FechaUC { get; set; }
        public decimal ExistenCon { get; set; }
        public decimal ExUnidadCon { get; set; }
        public string EdoABP { get; set; }
        public short Activo { get; set; }
        public Nullable<decimal> PrecioU2 { get; set; }
        public Nullable<decimal> PrecioU3 { get; set; }
        public decimal Peso { get; set; }
        public decimal Volumen { get; set; }
        public string UndVol { get; set; }
        public short EsReten { get; set; }
        public int DiasTole { get; set; }
    }
}
