//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPVPR
    {
        public string CodProv { get; set; }
        public string Refere { get; set; }
        public string TipoCom { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Costo { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public string NumeroD { get; set; }
        public int NROUNICO { get; set; }
        public short EsServ { get; set; }
        public string CodItem { get; set; }
    }
}
