//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SARGOTJT
    {
        public string CodTarj { get; set; }
        public int TipoRgo { get; set; }
        public int NroUnico { get; set; }
        public decimal Desde { get; set; }
        public decimal Hasta { get; set; }
        public decimal Monto { get; set; }
    }
}
