//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SASERV
    {
        public string CodServ { get; set; }
        public string Descrip { get; set; }
        public string Descrip2 { get; set; }
        public string Descrip3 { get; set; }
        public string Clase { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Precio1 { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public decimal Costo { get; set; }
        public short EsExento { get; set; }
        public short EsPorCost { get; set; }
        public short UsaServ { get; set; }
        public decimal Comision { get; set; }
        public short EsPorComi { get; set; }
        public Nullable<System.DateTime> FechaUV { get; set; }
        public Nullable<System.DateTime> FechaUC { get; set; }
        public int CodInst { get; set; }
        public Nullable<decimal> PrecioI1 { get; set; }
        public Nullable<decimal> PrecioI2 { get; set; }
        public Nullable<decimal> PrecioI3 { get; set; }
        public decimal EsImport { get; set; }
        public short Activo { get; set; }
        public short EsReten { get; set; }
        public short EsVenta { get; set; }
        public short EsCompra { get; set; }
    }
}
