//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SASUCURSAL
    {
        public string CodSucu { get; set; }
        public string Descrip { get; set; }
        public string Direc1 { get; set; }
        public string Direc2 { get; set; }
        public string Telef { get; set; }
        public int Pais { get; set; }
        public int Estado { get; set; }
        public int Ciudad { get; set; }
        public int Municipio { get; set; }
        public string ZipCode { get; set; }
    }
}
