//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATARJ
    {
        public string CodTarj { get; set; }
        public string Descrip { get; set; }
        public string Clase { get; set; }
        public decimal Impuesto { get; set; }
        public int DiasDif { get; set; }
        public decimal BaseReten { get; set; }
        public short Activo { get; set; }
        public decimal RetenIVA { get; set; }
        public short TipoIns { get; set; }
    }
}
