//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATAXITC
    {
        public string TipoCom { get; set; }
        public int NroLinea { get; set; }
        public string CodTaxs { get; set; }
        public string CodItem { get; set; }
        public decimal Monto { get; set; }
        public decimal TGRAVABLE { get; set; }
        public decimal MTOTAX { get; set; }
        public string NumeroD { get; set; }
        public string CodProv { get; set; }
        public string CodSucu { get; set; }
        public int NroLineaC { get; set; }
    }
}
