//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATAXVTAHist
    {
        public string TipoFac { get; set; }
        public string NumeroD { get; set; }
        public string CodTaxs { get; set; }
        public decimal Monto { get; set; }
        public decimal MtoTax { get; set; }
        public decimal TGravable { get; set; }
    }
}
