//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATAXES
    {
        public string CodTaxs { get; set; }
        public string Descrip { get; set; }
        public decimal MtoTax { get; set; }
        public short EsPorct { get; set; }
        public short EsCosto { get; set; }
        public short EsLibroI { get; set; }
        public short EsPartic { get; set; }
        public short Activo { get; set; }
        public short TipoIVA { get; set; }
        public short EsTaxVenta { get; set; }
        public short EsTaxCompra { get; set; }
        public short EsFijo { get; set; }
        public short EsReten { get; set; }
        public string CodOper { get; set; }
        public decimal MontoMax { get; set; }
        public decimal Sustraendo { get; set; }
    }
}
