//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATMPCHQ
    {
        public int NroUnico { get; set; }
        public decimal Monto { get; set; }
        public string Descrip { get; set; }
        public Nullable<System.DateTime> FechaE { get; set; }
        public string CodSucu { get; set; }
    }
}
