//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAVEND_01
    {
        public string CodVend { get; set; }
        public string usuario { get; set; }
        public string Clave { get; set; }
        public string Departamento { get; set; }
        public string Cargo { get; set; }
        public string Fecha_Ingreso { get; set; }
    }
}
