//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAZRP
    {
        public string Model { get; set; }
        public string NAH { get; set; }
        public int NroZ { get; set; }
        public System.DateTime DateZ { get; set; }
        public decimal TVenEx { get; set; }
        public decimal TVenA { get; set; }
        public decimal TVenB { get; set; }
        public decimal TVenC { get; set; }
        public decimal VImpA { get; set; }
        public decimal VImpB { get; set; }
        public decimal VImpC { get; set; }
        public decimal TDevEx { get; set; }
        public decimal TDevA { get; set; }
        public decimal TDevB { get; set; }
        public decimal TDevC { get; set; }
        public decimal DImpA { get; set; }
        public decimal DImpB { get; set; }
        public decimal DImpC { get; set; }
        public decimal AntCF { get; set; }
        public decimal UltCF { get; set; }
        public decimal AntNF { get; set; }
        public decimal UltNF { get; set; }
        public int Bsf { get; set; }
        public System.DateTime DateIn { get; set; }
        public short Tipo { get; set; }
        public decimal AntNC { get; set; }
        public decimal UltNC { get; set; }
        public int Cambio { get; set; }
        public bool Error { get; set; }
    }
}
