//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBAPPD
    {
        public int NroUnico { get; set; }
        public int NroPpal { get; set; }
        public string CodBanc { get; set; }
        public string Documento { get; set; }
        public string RIF { get; set; }
        public string Descripcion { get; set; }
        public string DescripPago { get; set; }
        public decimal Monto { get; set; }
        public string NumeroD { get; set; }
    }
}
