//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBAPPM
    {
        public int NroUnico { get; set; }
        public string CodBanc { get; set; }
        public string NroCtrl { get; set; }
        public System.DateTime FechaP { get; set; }
        public int NroPagos { get; set; }
        public int MtoPagos { get; set; }
    }
}
