//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBBANC
    {
        public string Descripcion { get; set; }
        public string NoCuenta { get; set; }
        public string Sucursal { get; set; }
        public int TDC { get; set; }
        public string CtaContab { get; set; }
        public decimal SaldoAct { get; set; }
        public decimal SaldoC1 { get; set; }
        public Nullable<System.DateTime> FechaC1 { get; set; }
        public decimal SaldoC2 { get; set; }
        public Nullable<System.DateTime> FechaC2 { get; set; }
        public int PrxConc { get; set; }
        public int InvChe { get; set; }
        public int IDB { get; set; }
        public string Moneda { get; set; }
        public decimal PDB { get; set; }
        public string CtaDebito { get; set; }
        public int PrxNDDB { get; set; }
        public int CtaConc { get; set; }
        public int RTransf { get; set; }
        public string NomSuc { get; set; }
        public int Pais { get; set; }
        public int Estado { get; set; }
        public int Ciudad { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion2 { get; set; }
        public string Gerente { get; set; }
        public string Telefonos { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Memo { get; set; }
        public int MesesH { get; set; }
        public int VNoCh { get; set; }
        public int VNoDp { get; set; }
        public int VNoNc { get; set; }
        public int VNoNd { get; set; }
        public decimal PrxCheque { get; set; }
        public string CodBanc { get; set; }
        public int NCOMP0 { get; set; }
        public int NCOMP1 { get; set; }
        public int NCOMP2 { get; set; }
        public int NCOMP3 { get; set; }
        public int NCOMP4 { get; set; }
        public int NCOMP5 { get; set; }
        public string ZipCode { get; set; }
        public int Municipio { get; set; }
        public Nullable<int> Activo { get; set; }
    }
}
