//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBBENE
    {
        public string CodBene { get; set; }
        public string Descripcion { get; set; }
        public string IOE { get; set; }
        public int Pais { get; set; }
        public int Estado { get; set; }
        public int Ciudad { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion2 { get; set; }
        public string Telefonos { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Memo { get; set; }
        public string Concepto1 { get; set; }
        public string Concepto2 { get; set; }
        public string Concepto3 { get; set; }
        public decimal Monto { get; set; }
        public string Coment1 { get; set; }
        public string Coment2 { get; set; }
        public string Coment3 { get; set; }
        public Nullable<System.DateTime> FechaI { get; set; }
        public Nullable<System.DateTime> UFecha { get; set; }
        public string UDcto { get; set; }
        public string UBenef { get; set; }
        public string UComent1 { get; set; }
        public string UComent2 { get; set; }
        public decimal UMonto { get; set; }
        public string CodCta { get; set; }
        public string UBanco { get; set; }
        public int ECG { get; set; }
        public string Movil { get; set; }
        public string ZipCode { get; set; }
        public int Municipio { get; set; }
    }
}
