//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBCONF
    {
        public decimal MaxCheque { get; set; }
        public int DiasD1 { get; set; }
        public int DiasD2 { get; set; }
        public int DiasD3 { get; set; }
        public int IChequeNE { get; set; }
        public int ICEgreso { get; set; }
        public int PrxCEgreso { get; set; }
        public int PrxDeposito { get; set; }
        public int PrxNDebito { get; set; }
        public int PrxNCredito { get; set; }
        public decimal PDebBan { get; set; }
        public int MesesH { get; set; }
        public string StDta { get; set; }
        public int AlertarND { get; set; }
        public int MOpeConc { get; set; }
        public int Consolida { get; set; }
        public string DirContab { get; set; }
        public string DirDtaCont { get; set; }
        public int ACtas0 { get; set; }
        public int ACtas1 { get; set; }
        public int ACtas2 { get; set; }
        public int ACtas3 { get; set; }
        public int ACtas4 { get; set; }
        public int ACtas5 { get; set; }
        public int NOpe1 { get; set; }
        public int NOpe2 { get; set; }
        public int NOpe3 { get; set; }
        public int NOpe4 { get; set; }
        public int NOpe5 { get; set; }
        public int NOpe6 { get; set; }
        public int NOpe7 { get; set; }
        public int NOpe8 { get; set; }
        public int NOpe9 { get; set; }
        public int NOpe10 { get; set; }
        public string CtaAux1 { get; set; }
        public string CtaAux2 { get; set; }
        public string CtaAux3 { get; set; }
        public Nullable<int> CCTipo { get; set; }
        public string CCDescrip { get; set; }
        public Nullable<int> CCSsw { get; set; }
        public string CCServer { get; set; }
        public string CCDb { get; set; }
        public string CCUser { get; set; }
        public string CCPwd { get; set; }
        public Nullable<int> CCPrefix { get; set; }
        public int NroCxB { get; set; }
    }
}
