//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBCTAP
    {
        public string ID3 { get; set; }
        public string CodBanc { get; set; }
        public string Descripcion { get; set; }
        public string NroCuenta { get; set; }
    }
}
