//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBCTAS
    {
        public string Descripcion { get; set; }
        public int IEA { get; set; }
        public string Grupo { get; set; }
        public Nullable<System.DateTime> UFecha { get; set; }
        public string UDcto { get; set; }
        public string UBenef { get; set; }
        public string UComent1 { get; set; }
        public string UComent2 { get; set; }
        public decimal UMonto { get; set; }
        public int EsBanco { get; set; }
        public int TDC { get; set; }
        public decimal SaldoAct { get; set; }
        public string Tercero { get; set; }
        public string CodCentro { get; set; }
        public int CtaCF { get; set; }
        public int CtaMov { get; set; }
        public int CtaTer { get; set; }
        public int CtaCC { get; set; }
        public int CtaBase { get; set; }
        public string CodCta { get; set; }
        public string UBanco { get; set; }
        public int ECG { get; set; }
    }
}
