//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBDEFPD
    {
        public int NDefAPP { get; set; }
        public int TipoCDT { get; set; }
        public int NLinea { get; set; }
        public int NCampo { get; set; }
        public int TipoDat { get; set; }
        public string Data { get; set; }
        public string Formato { get; set; }
    }
}
