//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBDIFE
    {
        public int NOpe { get; set; }
        public int NLinea { get; set; }
        public string CodUsua { get; set; }
        public string CodEsta { get; set; }
        public int CDCD { get; set; }
        public string Documento { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaLib { get; set; }
        public string Beneficiario { get; set; }
        public string TipoPgo { get; set; }
        public string DescPgo { get; set; }
        public string DctoPgo { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public int TipoOpe { get; set; }
        public decimal MontoE { get; set; }
        public string NBanco { get; set; }
        public string NumeroC { get; set; }
        public int PlazaC { get; set; }
        public decimal MontoC { get; set; }
        public Nullable<System.DateTime> FechaC { get; set; }
        public string CodTarj { get; set; }
        public string Descrip { get; set; }
        public decimal MontoBT { get; set; }
        public decimal BaseIT { get; set; }
        public decimal ComiT { get; set; }
        public decimal ImpT { get; set; }
        public decimal NetoT { get; set; }
        public Nullable<System.DateTime> FechaT { get; set; }
        public string CodBanc { get; set; }
    }
}
