//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBDOpF
    {
        public string NroUnico { get; set; }
        public string CodOpFr { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public decimal Monto2 { get; set; }
        public string Comentario { get; set; }
        public string Comentario1 { get; set; }
        public string Comentario2 { get; set; }
        public string CodCta { get; set; }
        public string CodBene { get; set; }
        public string CodCenCto { get; set; }
    }
}
