//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBOpFr
    {
        public string CodOpFr { get; set; }
        public string Descripcion { get; set; }
        public string CodBene { get; set; }
        public int TipoOpe { get; set; }
        public System.DateTime FechaPP { get; set; }
        public int Avisar { get; set; }
        public int Siempre { get; set; }
        public int NPagos { get; set; }
        public int Frecuencia { get; set; }
        public decimal Monto { get; set; }
    }
}
