//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBOPCTAS
    {
        public string CodProv { get; set; }
        public string NroOPago { get; set; }
        public int NroILB { get; set; }
        public int NroLinea { get; set; }
        public int Estado { get; set; }
        public string SData { get; set; }
        public decimal FData { get; set; }
    }
}
