//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBOPCXPP
    {
        public int NroUnico { get; set; }
        public string CodProv { get; set; }
        public int Estado { get; set; }
        public int EdoPago { get; set; }
        public int NroIDOP { get; set; }
        public string Clase { get; set; }
        public string CodBanc { get; set; }
        public System.DateTime FechaE { get; set; }
        public string CodOper { get; set; }
        public string CodBene { get; set; }
        public string Descripcion { get; set; }
        public string NroOPago { get; set; }
        public string Documento { get; set; }
        public int NroUTrnB { get; set; }
        public string NumeroD { get; set; }
        public string Document { get; set; }
        public int NroURecP { get; set; }
        public int NroURetP { get; set; }
        public int NroDcts { get; set; }
        public decimal Monto { get; set; }
        public decimal MtoPagos { get; set; }
        public decimal MtoReten { get; set; }
        public decimal Porcent { get; set; }
        public int UsaIDB { get; set; }
        public string CtaIDB { get; set; }
        public string DCtaIDB { get; set; }
        public string CenCtoIdb { get; set; }
        public decimal MtoIDB { get; set; }
        public string Notas1 { get; set; }
        public string Notas2 { get; set; }
        public string Notas3 { get; set; }
        public string Notas4 { get; set; }
        public string Notas5 { get; set; }
        public string Notas6 { get; set; }
        public string Notas7 { get; set; }
        public string Notas8 { get; set; }
        public string Notas9 { get; set; }
        public string Notas10 { get; set; }
        public string Comentario1 { get; set; }
        public string Comentario2 { get; set; }
        public string Comentario3 { get; set; }
    }
}
