//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBPres
    {
        public int TipoAcum { get; set; }
        public string Periodo { get; set; }
        public decimal Debitos { get; set; }
        public decimal Creditos { get; set; }
        public string CodCta { get; set; }
    }
}
