//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBPrxC
    {
        public int NroUnico { get; set; }
        public string Numero { get; set; }
        public int Estado { get; set; }
        public string CodBene { get; set; }
        public string Beneficiario { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string CodBanc { get; set; }
    }
}
