//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBRptD
    {
        public string Unico { get; set; }
        public string CodBanco { get; set; }
        public string NroCuenta { get; set; }
        public string DesBanco { get; set; }
        public string TipBanco { get; set; }
        public string TitRpt1 { get; set; }
        public string TitRpt2 { get; set; }
        public string TitRpt3 { get; set; }
        public string TitRpt4 { get; set; }
        public string TitRpt5 { get; set; }
        public Nullable<System.DateTime> FecRpt1 { get; set; }
        public Nullable<System.DateTime> FecRpt2 { get; set; }
        public Nullable<System.DateTime> FecRpt3 { get; set; }
        public Nullable<System.DateTime> FecRpt4 { get; set; }
        public Nullable<System.DateTime> FecRpt5 { get; set; }
        public decimal MtoRpt1 { get; set; }
        public decimal MtoRpt2 { get; set; }
        public decimal MtoRpt3 { get; set; }
        public decimal MtoRpt4 { get; set; }
        public decimal MtoRpt5 { get; set; }
        public string MtoTxt1 { get; set; }
        public string MtoTxt2 { get; set; }
        public string MtoTxt3 { get; set; }
        public string MtoTxt4 { get; set; }
        public string MtoTxt5 { get; set; }
    }
}
