//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBTrTr
    {
        public System.DateTime Fecha { get; set; }
        public string AOD { get; set; }
        public int NOpe { get; set; }
        public int NoConc { get; set; }
        public string CodUsua { get; set; }
        public System.DateTime FechaLib { get; set; }
        public string CodBene { get; set; }
        public int TDC { get; set; }
        public int CDCD { get; set; }
        public string Descripcion { get; set; }
        public string Documento { get; set; }
        public string Comentario1 { get; set; }
        public string Comentario2 { get; set; }
        public string Comentario3 { get; set; }
        public string OBCP { get; set; }
        public string Origen { get; set; }
        public int Estado { get; set; }
        public decimal Monto { get; set; }
        public decimal MtoDb { get; set; }
        public decimal MtoCr { get; set; }
        public decimal Monto1 { get; set; }
        public decimal Monto2 { get; set; }
        public decimal Saldo { get; set; }
        public string CodBanc { get; set; }
        public string CRefer { get; set; }
    }
}
