//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBTRAN
    {
        public System.DateTime Fecha { get; set; }
        public string AOD { get; set; }
        public int NOpe { get; set; }
        public int NroComp { get; set; }
        public int OpeRel { get; set; }
        public string CodUsua { get; set; }
        public string CodOper { get; set; }
        public string CodEsta { get; set; }
        public System.DateTime FechaLib { get; set; }
        public int TipBen { get; set; }
        public string CodBene { get; set; }
        public int TDC { get; set; }
        public int CDCD { get; set; }
        public string Descripcion { get; set; }
        public string Documento { get; set; }
        public string Comentario1 { get; set; }
        public string Comentario2 { get; set; }
        public string Comentario3 { get; set; }
        public string Memo { get; set; }
        public string OBCP { get; set; }
        public string Origen { get; set; }
        public int Estado { get; set; }
        public System.DateTime FecConc { get; set; }
        public int NoConc { get; set; }
        public decimal Monto { get; set; }
        public decimal MtoDb { get; set; }
        public decimal MtoCr { get; set; }
        public int TipoOpe { get; set; }
        public string DCtaIDB { get; set; }
        public decimal MtoIDB { get; set; }
        public int Consolidado { get; set; }
        public Nullable<System.DateTime> FConsolidado { get; set; }
        public decimal NroEgreso { get; set; }
        public decimal MtoDebito { get; set; }
        public string DctoOrigen { get; set; }
        public decimal MtoOrigen { get; set; }
        public string BeneOrigen { get; set; }
        public decimal Monto1 { get; set; }
        public decimal Monto2 { get; set; }
        public decimal MtoDeb { get; set; }
        public string DctoOri { get; set; }
        public string BeneOri { get; set; }
        public decimal MtoOri { get; set; }
        public decimal Saldo { get; set; }
        public int NroPpal { get; set; }
        public int Endosable { get; set; }
        public string CodBanc { get; set; }
        public string CRefer { get; set; }
        public string CtaIDB { get; set; }
        public string CodSucu { get; set; }
    }
}
