//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFTITM
    {
        public int itemid { get; set; }
        public int folderid { get; set; }
        public string itemname { get; set; }
        public Nullable<int> itemsize { get; set; }
        public int itemtype { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<System.DateTime> deleted { get; set; }
        public byte[] template { get; set; }
    }
}
