//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRCCP
    {
        public string WFecha { get; set; }
        public string Wst { get; set; }
        public Nullable<System.DateTime> FECHAE { get; set; }
        public string NumeroF { get; set; }
        public string NumeroD { get; set; }
        public string TipoFac { get; set; }
        public string CodVend { get; set; }
        public string Cliente { get; set; }
        public Nullable<decimal> Contado { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<decimal> TotOperacion { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Adelanto { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Cheque { get; set; }
        public Nullable<decimal> Tarjeta { get; set; }
        public Nullable<decimal> Fletes { get; set; }
        public Nullable<decimal> Descuentos { get; set; }
        public Nullable<decimal> Ventas { get; set; }
        public Nullable<decimal> RetenIVA { get; set; }
        public Nullable<decimal> TotalPrd { get; set; }
        public Nullable<decimal> TotalSrv { get; set; }
        public Nullable<decimal> TExento { get; set; }
        public int TFac { get; set; }
        public int TDev { get; set; }
        public decimal MtoTotalDev { get; set; }
        public Nullable<decimal> MtoBaseEF { get; set; }
        public decimal MtoBaseF { get; set; }
        public decimal MtoTaxF { get; set; }
        public int NroF { get; set; }
        public Nullable<decimal> MtoBaseED { get; set; }
        public decimal MtoBaseD { get; set; }
        public decimal MtoTaxD { get; set; }
        public int NroD { get; set; }
    }
}
