//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSAUTR
    {
        public string CodAutr { get; set; }
        public int Modulo { get; set; }
        public int Parametro { get; set; }
        public string Autoriza { get; set; }
    }
}
