//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSFLDS
    {
        public string CodNivl { get; set; }
        public string Tabla { get; set; }
        public int NCampo { get; set; }
        public string Descrip { get; set; }
        public int Activo { get; set; }
        public int Editable { get; set; }
    }
}
