//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSOPMN
    {
        public string CodMenu { get; set; }
        public string CodOpMn { get; set; }
        public int Nivel { get; set; }
        public int Accion { get; set; }
        public int OpActiva { get; set; }
        public int UPrinter { get; set; }
        public string SSFld { get; set; }
        public string Nombre { get; set; }
    }
}
