//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSPARD
    {
        public string CodParm { get; set; }
        public int Modulo { get; set; }
        public int Parametro { get; set; }
        public int NoData { get; set; }
        public int TipoData { get; set; }
        public int IData { get; set; }
        public string SData { get; set; }
        public decimal FData { get; set; }
        public string SSFld { get; set; }
    }
}
