//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSPARM
    {
        public string CodParm { get; set; }
        public int Modulo { get; set; }
        public int Parametro { get; set; }
        public int Activo { get; set; }
        public int Clave { get; set; }
        public int Habilitado { get; set; }
        public string SSFld { get; set; }
    }
}
