//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSTRACE
    {
        public int NroUnico { get; set; }
        public string CodEsta { get; set; }
        public string CodUsua { get; set; }
        public string DesUsua { get; set; }
        public string CodUEst { get; set; }
        public string DesUEst { get; set; }
        public string SisSnt { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
    }
}
