//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSUSRS
    {
        public string CodUsua { get; set; }
        public string Descrip { get; set; }
        public string EMail { get; set; }
        public string UsrDta1 { get; set; }
        public string UsrDta2 { get; set; }
        public string UsrDta3 { get; set; }
        public string UsrDta4 { get; set; }
        public string UsrDta5 { get; set; }
        public string SData1 { get; set; }
        public string SData2 { get; set; }
        public string SData3 { get; set; }
        public string Movil { get; set; }
        public string CodVend { get; set; }
        public int IdUserNot { get; set; }
        public string Profile { get; set; }
        public string UserId { get; set; }
    }
}
