//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class STIB01
    {
        public int NOpe { get; set; }
        public string DesBanco { get; set; }
        public string NoCuenta { get; set; }
        public string NroDcto { get; set; }
        public int NroComp { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string FechaA { get; set; }
        public string FechaM { get; set; }
        public string FechaD { get; set; }
        public int TipBen { get; set; }
        public string CodBene { get; set; }
        public string AOD { get; set; }
        public int TDC { get; set; }
        public string DesTDC { get; set; }
        public int CDCD { get; set; }
        public string Descripcion { get; set; }
        public string Comentario1 { get; set; }
        public string Comentario2 { get; set; }
        public string Comentario3 { get; set; }
        public decimal MtoOp { get; set; }
        public decimal MtoDb { get; set; }
        public decimal MtoCr { get; set; }
        public decimal MtoEfe { get; set; }
        public decimal MtoChe { get; set; }
        public decimal MtoTar { get; set; }
        public string MtoTxt1 { get; set; }
        public string MtoTxt2 { get; set; }
        public string MtoTxt3 { get; set; }
        public string CodBanco { get; set; }
    }
}
