//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class STIB02
    {
        public int NOpe { get; set; }
        public string CodCta { get; set; }
        public string DesCta { get; set; }
        public string Descripcion { get; set; }
        public decimal MtoOp { get; set; }
        public decimal MtoDb { get; set; }
        public decimal MtoCr { get; set; }
    }
}
