//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXAuditProd
    {
        public System.DateTime Fecha { get; set; }
        public string Usuario { get; set; }
        public string Accion { get; set; }
        public string CodProd { get; set; }
        public string Descrip { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> CodInst { get; set; }
        public Nullable<decimal> Existen { get; set; }
        public Nullable<decimal> CostoAct { get; set; }
        public Nullable<decimal> CostoPro { get; set; }
        public Nullable<decimal> CostoAnt { get; set; }
        public Nullable<decimal> Precio1 { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public Nullable<decimal> Compro { get; set; }
    }
}
