//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_GERENCIA_STIB01
    {
        public Nullable<int> NOpe { get; set; }
        public string CodBanco { get; set; }
        public string DesBanco { get; set; }
        public string NoCuenta { get; set; }
        public string NroDcto { get; set; }
        public string NroComp { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string FechaA { get; set; }
        public string FechaM { get; set; }
        public string FechaD { get; set; }
        public Nullable<int> TipBen { get; set; }
        public string CodBene { get; set; }
        public string AOD { get; set; }
        public Nullable<int> TDC { get; set; }
        public string DesTDC { get; set; }
        public Nullable<int> CDCD { get; set; }
        public string Descripcion { get; set; }
        public string Comentario1 { get; set; }
        public string Comentario2 { get; set; }
        public string Comentario3 { get; set; }
        public Nullable<decimal> MtoOp { get; set; }
        public Nullable<decimal> MtoDb { get; set; }
        public Nullable<decimal> MtoCr { get; set; }
        public Nullable<decimal> MtoEfe { get; set; }
        public Nullable<decimal> MtoChe { get; set; }
        public Nullable<decimal> MtoTar { get; set; }
        public string MtoTxt1 { get; set; }
        public string MtoTxt2 { get; set; }
        public string MtoTxt3 { get; set; }
    }
}
