//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentrix.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_TRANRESPROD
    {
        public decimal ID { get; set; }
        public string CodTabla { get; set; }
        public string CodItem { get; set; }
        public string Descrip1 { get; set; }
        public string Unidad { get; set; }
        public Nullable<double> ExActual { get; set; }
        public Nullable<double> Cant { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Utilidad { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<int> EsUnid { get; set; }
    }
}
